# Generated by Django 4.1.5 on 2023-01-03 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meetings_Type', models.CharField(max_length=100)),
                ('Meeting_Name', models.CharField(max_length=100)),
                ('Meeting_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_class', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_Religion', models.CharField(max_length=100)),
                ('student_Joining_date', models.DateTimeField(auto_now_add=True)),
                ('student_Section', models.CharField(max_length=100)),
                ('student_father_name', models.CharField(max_length=100)),
                ('student_father_occupation', models.CharField(max_length=100)),
                ('student_father_number', models.CharField(max_length=100)),
                ('studen_present_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studen_permanent_addres', models.TextField()),
                ('Student_photo', models.ImageField(upload_to='media/Students_photos')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_gender', models.CharField(max_length=100)),
                ('staff_subject', models.CharField(max_length=100)),
                ('staff_mobile', models.CharField(max_length=19)),
                ('staff_Qualification', models.CharField(max_length=100)),
                ('staff_Experience', models.CharField(max_length=100)),
                ('CitizenCard_Number', models.CharField(max_length=30)),
                ('staff_sellery', models.CharField(max_length=100)),
                ('staff_address', models.TextField()),
                ('staff_photo', models.ImageField(upload_to='media/Teacher_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
