# Generated by Django 4.1.5 on 2023-01-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_class_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
