# Generated by Django 4.1.5 on 2023-01-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0005_class_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='Class',
            new_name='Class_Name',
        ),
    ]
