# Generated by Django 4.1.5 on 2023-01-05 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_rename_class_section_class_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
