# Generated by Django 4.1.5 on 2023-01-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0007_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=100)),
                ('student_gender', models.CharField(max_length=100)),
                ('student_dob', models.DateField()),
                ('student_Religion', models.CharField(max_length=100)),
                ('student_Joining_date', models.DateTimeField(auto_now_add=True)),
                ('student_Section', models.CharField(max_length=100)),
                ('student_father_name', models.CharField(max_length=100)),
                ('student_father_occupation', models.CharField(max_length=100)),
                ('student_father_number', models.CharField(max_length=100)),
                ('studen_present_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('studen_permanent_addres', models.TextField()),
                ('Student_photo', models.ImageField(upload_to='media/Students_photos')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.class')),
            ],
        ),
    ]
