# Generated by Django 4.1.5 on 2023-01-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0011_alter_student_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_Section',
            field=models.CharField(max_length=100),
        ),
    ]
