# Generated by Django 4.1.5 on 2023-01-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0018_alter_staff_notifica_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_leave',
            name='leave_date',
        ),
        migrations.RemoveField(
            model_name='student_leave',
            name='leave_date',
        ),
        migrations.AlterField(
            model_name='guest_notification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
