# Generated by Django 4.1.5 on 2023-01-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0021_staff_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_feedback',
            name='feedback_subject',
            field=models.CharField(default='', max_length=100),
        ),
    ]
