# Generated by Django 4.1.5 on 2023-01-14 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0022_staff_feedback_feedback_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_subject', models.CharField(default='', max_length=100)),
                ('feedback_reply', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('guest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.student')),
            ],
        ),
    ]
