# Generated by Django 4.1.5 on 2023-01-26 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0026_delete_attendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.student')),
            ],
        ),
    ]
