# Generated by Django 4.1.5 on 2023-01-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0027_attendancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
