# Generated by Django 4.1.5 on 2023-01-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0029_attendancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
