# Generated by Django 4.1.5 on 2023-01-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0031_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='Meetings_Type',
            field=models.IntegerField(default=2),
        ),
    ]
