# Generated by Django 4.1.5 on 2023-01-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0032_alter_meetings_meetings_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meetings',
        ),
    ]
