# Generated by Django 4.1.5 on 2023-01-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0033_delete_meetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meetings_Type', models.IntegerField(default=2)),
                ('Meeting_Name', models.CharField(max_length=100)),
                ('Meeting_Date', models.DateField()),
            ],
        ),
    ]
