# Generated by Django 4.1.5 on 2023-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0034_meetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Events_Name', models.CharField(max_length=100)),
                ('Events_Date', models.DateField()),
                ('Events_Discription', models.TextField()),
            ],
        ),
    ]
