# Generated by Django 4.1.5 on 2023-02-02 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0035_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=None)),
                ('update_at', models.DateTimeField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='class',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='class',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='events',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='guest_notification',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='guest_notification',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='meetings',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='meetings',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='section',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='section',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='guest_feedback',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='guest_feedback',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='guest_notification',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_feedback',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_feedback',
            name='update_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='staff_notifica',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_Joining_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student_leave',
            name='updated_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Day', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('create_at', models.DateTimeField(default=None)),
                ('update_at', models.DateTimeField(default=None)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.subjects')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='Subject_Section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.section'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='Subject_Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staff'),
        ),
    ]
