# Generated by Django 4.1.5 on 2023-02-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0037_alter_attendancerecord_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='Other',
            field=models.IntegerField(default=0),
        ),
    ]
