# Generated by Django 4.1.5 on 2023-02-04 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0038_timetable_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='Class_Teacher',
        ),
        migrations.AddField(
            model_name='staff',
            name='class_Teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.section'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_Feedback',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_sellery',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject_Name', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('Subject_Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.section')),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.subject'),
        ),
    ]
