# Generated by Django 4.1.6 on 2023-02-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0039_remove_section_class_teacher_staff_class_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_Feedback',
            field=models.TextField(default='Hi'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.subject'),
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
