# Generated by Django 4.1.6 on 2023-02-14 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0041_timetable_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.section'),
        ),
    ]
