# Generated by Django 4.1.6 on 2023-02-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0042_alter_timetable_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='staff_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staff'),
        ),
    ]
