# Generated by Django 4.1.6 on 2023-02-16 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0044_alter_timetable_staff_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='Other',
        ),
    ]
