# Generated by Django 4.1.6 on 2023-02-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0046_examevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='Annual_Fee',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='class',
            name='Exams_Fee',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='class',
            name='Monthly_Fee',
            field=models.IntegerField(default=2400),
        ),
    ]
