# Generated by Django 4.1.6 on 2023-02-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0048_fees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='payment_date',
            field=models.DateField(default=None),
        ),
    ]
