# Generated by Django 4.1.6 on 2023-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0049_alter_fees_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fees',
            name='payment_date',
            field=models.BooleanField(default=False),
        ),
    ]
