# Generated by Django 4.1.6 on 2023-02-28 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0050_alter_fees_payment_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fees',
            old_name='payment_date',
            new_name='payed',
        ),
    ]
