# Generated by Django 4.1.6 on 2023-03-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0052_facility_hostel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='room_numbers',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='room_types',
        ),
        migrations.AddField(
            model_name='room',
            name='fees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.fees'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='BackEnd.hostel'),
        ),
    ]
