# Generated by Django 4.1.6 on 2023-03-05 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0053_remove_hostel_fees_remove_hostel_room_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='fees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.fees'),
        ),
    ]
