# Generated by Django 4.1.6 on 2023-03-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0055_hostel_hostel_photo_room_rooms_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='hostel_photo',
            field=models.ImageField(upload_to='media/Hostel_Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rooms_photo',
            field=models.ImageField(upload_to='media/Rooms_Image'),
        ),
    ]
