# Generated by Django 4.1.6 on 2023-03-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0056_alter_hostel_hostel_photo_alter_room_rooms_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='room_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
