# Generated by Django 4.1.6 on 2023-03-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0058_alter_room_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostelers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('hosteler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.student')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.room')),
            ],
        ),
    ]
