# Generated by Django 4.1.6 on 2023-03-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0059_hostelers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostelers',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostelers', to='BackEnd.room'),
        ),
    ]
