# Generated by Django 4.1.6 on 2023-03-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0061_staff_types'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff',
            new_name='Teacher',
        ),
        migrations.CreateModel(
            name='Staffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_gender', models.CharField(max_length=100)),
                ('staff_mobile', models.CharField(max_length=19)),
                ('staff_Experience', models.CharField(max_length=100)),
                ('CitizenCard_Number', models.CharField(max_length=30)),
                ('staff_sellery', models.IntegerField(default=100)),
                ('staff_address', models.TextField()),
                ('staff_photo', models.ImageField(upload_to='media/staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Staff_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staff_types')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
