# Generated by Django 4.1.6 on 2023-03-11 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0062_rename_staff_teacher_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='warden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staffs'),
        ),
    ]
