# Generated by Django 4.1.6 on 2023-03-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0065_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.CharField(default='i', max_length=100)),
                ('leave_subject', models.CharField(default='iam', max_length=100)),
                ('Application', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('feedback_subject', models.CharField(default='', max_length=100)),
                ('feedback_reply', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.teacher')),
            ],
        ),
    ]
