# Generated by Django 4.1.6 on 2023-03-18 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0066_teacher_notification_teacher_leave_teacher_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_feedback',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staffs'),
        ),
        migrations.AlterField(
            model_name='staff_leave',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staffs'),
        ),
        migrations.AlterField(
            model_name='staff_notifica',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.staffs'),
        ),
    ]
