# Generated by Django 4.1.6 on 2023-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0067_alter_staff_feedback_staff_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicles',
            old_name='vehicle_name',
            new_name='vehicle_type',
        ),
        migrations.AddField(
            model_name='vehicles',
            name='vehicles_photo',
            field=models.ImageField(default='1.png', upload_to='media/Vehicles_Img'),
        ),
    ]
