# Generated by Django 4.1.6 on 2023-03-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0068_rename_vehicle_name_vehicles_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicles_photo',
            field=models.ImageField(upload_to='media/Vehicles_Img'),
        ),
    ]
