# Generated by Django 4.1.6 on 2023-03-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0069_alter_vehicles_vehicles_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='location',
        ),
    ]
