# Generated by Django 4.1.6 on 2023-03-24 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0070_remove_stop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.route'),
        ),
    ]
