# Generated by Django 4.1.6 on 2023-03-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0072_alter_stop_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='route',
        ),
        migrations.AddField(
            model_name='stop',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.vehicles'),
        ),
    ]
