# Generated by Django 4.1.6 on 2023-03-24 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0073_remove_stop_route_stop_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.vehicles'),
        ),
    ]
