# Generated by Django 4.1.6 on 2023-03-24 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0074_alter_stop_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_rider',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riders', to='BackEnd.route'),
        ),
    ]
