# Generated by Django 4.1.6 on 2023-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0075_alter_bus_rider_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Full_Mark',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subject',
            name='Pactical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='Pass_Mark',
            field=models.IntegerField(default=75),
        ),
    ]
