# Generated by Django 4.1.6 on 2023-03-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0077_salarys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarys',
            name='employe',
            field=models.OneToOneField(limit_choices_to={'user_type__in': [2, 4]}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
