# Generated by Django 4.1.6 on 2023-03-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0078_alter_salarys_employe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffs',
            name='staff_sellery',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='staff_sellery',
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.OneToOneField(limit_choices_to={'user_type__in': [2, 4]}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='salarys',
            name='employe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.employe'),
        ),
    ]
