# Generated by Django 4.1.6 on 2023-03-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0079_remove_staffs_staff_sellery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarys',
            name='salary_type',
            field=models.CharField(default='Monthly Salary', max_length=100),
        ),
    ]
