# Generated by Django 4.1.6 on 2023-04-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0084_examevent_exam_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examevent',
            name='Exam_Session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.exam'),
        ),
    ]
