# Generated by Django 4.1.6 on 2023-04-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0085_alter_examevent_exam_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name',
            field=models.CharField(default='EXAM - ', max_length=100),
        ),
    ]
