# Generated by Django 4.1.6 on 2023-05-09 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0089_remove_result_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='Subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BackEnd.subject'),
        ),
    ]
