# Generated by Django 4.1.6 on 2023-04-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_category_image'),
        ('Blogs', '0003_remove_blog_section_blog_category_delete_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FrontEnd.category'),
        ),
    ]
