# Generated by Django 4.1.6 on 2023-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_alter_comment_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
