# Generated by Django 4.1.5 on 2023-01-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0002_rename_home_page_frontend_frist_home_page_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend',
            name='School_video',
        ),
    ]
