# Generated by Django 4.1.6 on 2023-04-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0004_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend',
            name='About_Cancution',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='About_Points',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='About_page',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='About_us',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Frist_Home_page_image',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Frist_title',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Frist_title_about',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Owner_Name',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='School_Name',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='School_Number',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='School_email',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Second_home_page_image',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Second_title',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Second_title_about',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Third_Home_page_image',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Thried_title',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='Thried_title_about',
        ),
        migrations.AddField(
            model_name='frontend',
            name='first_home_page_image',
            field=models.ImageField(default='a', upload_to='media/FrontEnd'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='first_title',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='first_title_about',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='third_title',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='third_title_about',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='about_us',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='address',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='owner_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='school_email',
            field=models.EmailField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='school_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='school_number',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='second_home_page_image',
            field=models.ImageField(default='a', upload_to='media/FrontEnd'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='second_title',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AddField(
            model_name='frontend',
            name='second_title_about',
            field=models.TextField(default='a'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='third_home_page_image',
            field=models.ImageField(default='a', upload_to='media/FrontEnd'),
        ),
    ]
