# Generated by Django 4.1.6 on 2023-04-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0006_alter_frontend_about_us_alter_frontend_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='about_us_media',
            field=models.FileField(default='', upload_to='media/FrontEnd'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='about_us_photo',
            field=models.ImageField(default='', upload_to='media/FrontEnd'),
        ),
    ]
