# Generated by Django 4.1.6 on 2023-04-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0007_frontend_about_us_media_frontend_about_us_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='about_us_media',
            field=models.FileField(upload_to='media/FrontEnd'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='about_us_photo',
            field=models.ImageField(upload_to='media/FrontEnd'),
        ),
    ]
