# Generated by Django 4.1.6 on 2023-04-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0009_rename_name_contact_first_name_contact_captcha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=100)),
                ('parent_phone', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=100)),
                ('child_dob', models.DateField()),
                ('child_grade', models.IntegerField()),
                ('child_school', models.CharField(max_length=100)),
                ('admission_type', models.CharField(max_length=100)),
                ('admission_deadline', models.DateField()),
                ('admission_documents', models.FileField(upload_to='admission_documents/')),
                ('admission_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
