# Generated by Django 4.1.6 on 2023-04-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0010_parenthelp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
