# Generated by Django 4.1.6 on 2023-04-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0015_alter_news_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontend',
            name='about_us',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='about_us_media',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='about_us_photo',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='first_home_page_image',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='first_title',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='first_title_about',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='school_email',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='school_number',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='second_home_page_image',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='second_title',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='second_title_about',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='third_home_page_image',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='third_title',
        ),
        migrations.RemoveField(
            model_name='frontend',
            name='third_title_about',
        ),
        migrations.AddField(
            model_name='frontend',
            name='about_image1',
            field=models.ImageField(default='', upload_to='about_images/'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='about_image2',
            field=models.ImageField(default='', upload_to='about_images/'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ceo_image',
            field=models.ImageField(default='', upload_to='ceo_images/'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='ceo_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='frontend',
            name='contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='frontend',
            name='facebook_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='frontend',
            name='hero_image',
            field=models.ImageField(default='', upload_to='hero_images/'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='instagram_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='frontend',
            name='linkedin_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='frontend',
            name='logo',
            field=models.ImageField(default='', upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='frontend',
            name='name',
            field=models.CharField(default='My School', max_length=200),
        ),
        migrations.AddField(
            model_name='frontend',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='frontend',
            name='twitter_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
