# Generated by Django 4.1.6 on 2023-04-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0016_remove_frontend_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontend',
            name='about_image1',
            field=models.ImageField(upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='about_image2',
            field=models.ImageField(upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='ceo_image',
            field=models.ImageField(upload_to='ceo_images/'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='ceo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='hero_image',
            field=models.ImageField(upload_to='hero_images/'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='logo',
            field=models.ImageField(upload_to='school_logos/'),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='frontend',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
