# Generated by Django 4.1.6 on 2023-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0017_alter_frontend_about_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='telephone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
