# Generated by Django 4.1.6 on 2023-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0018_frontend_telephone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontend',
            name='hero_image_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='frontend',
            name='intro',
            field=models.FileField(blank=True, default='', null=True, upload_to='intro'),
        ),
    ]
