# Generated by Django 4.1.6 on 2023-05-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FrontEnd', '0020_alter_frontend_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontend',
            options={'get_latest_by': 'id'},
        ),
    ]
